name: Fuzz
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fuzz:
    name: Fuzzing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.4' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: go envs
        run: go env
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: $GOCACHE/fuzz
          key: fuzz-${{ matrix.go-version }}-${{ hashFiles('jps_test.go') }}
          restore-keys: |
            fuzz-${{ matrix.go-version }}-
            fuzz-
      - name: Run tests with fuzzing
        run: go test -fuzz . -fuzztime=10s
